# Site settings
title: Institut Prospective
email: simons@simons.fr
description: > # this means to ignore newlines until "baseurl:."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: fab_mob
github_username:  fabmob
logo: 
# Build settings
markdown: kramdown
